### ISSUE TITLE
Importing rules_apple_line doesn't work

### ISSUE THREAD

**Issue by michaeleisel** [line/rules_apple_line#27]
After the headermap patch was added, it appears that importing fails. I import the library with:
```
    http_archive(
        name = "rules_apple_line",
        sha256 = "aaca7310c31733adace87393ace44dceef4bc18a315e2799d1de1bb56f65592f",
        strip_prefix = "rules_apple_line-200c811e5543c31769220617432425b4ae5e01db",
        url = "https://github.com/line/rules_apple_line/archive/200c811e5543c31769220617432425b4ae5e01db.tar.gz",
    )
```

And I get the error:
```
ERROR: An error occurred during the fetch of repository 'com_github_ob_rules_ios':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_meisel/f86a8c8f171499aca10fad369fca25ea/external/bazel_tools/tools/build_defs/repo/git.bzl", line 182, column 10, in _git_repository_implementation
		patch(ctx)
	File "/private/var/tmp/_bazel_meisel/f86a8c8f171499aca10fad369fca25ea/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Not a regular file: /Users/meisel/projects/c/third_party/rules_ios.patch
ERROR: Skipping '//base/Kids:KidsNew': no such package '@com_github_ob_rules_ios//rules': Not a regular file: /Users/meisel/projects/c/third_party/rules_ios.patch
ERROR: no such package '@com_github_ob_rules_ios//rules': Not a regular file: /Users/meisel/projects/c/third_party/rules_ios.patch
```
So, it looks like `//third_party:rules_ios.patch` is interpreted to be in my workspace, and not that of rules_apple_line's

**Comment by thii** [comment]
Sorry about that. Please try again with the latest.

**Comment by michaeleisel** [comment]
🙏
